config/routes.rb
Smart::Application.routes.draw do

  resources :users do
  member do
    get :following, :followers
  end
end
  get "password_resets/new"

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
   resources :password_resets
   resources :microposts, :only => [:create, :destroy]
   resources :relationships, :only => [:create, :destroy]

match '/contact', :to => 'pages#contact'
match '/about', :to => 'pages#about'
match '/help', :to => 'pages#help'
match '/front', :to => 'pages#front'

root :to => 'pages#home'

match '/signup', :to => 'users#new'
match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@user.errors.count, "error") %>
prohibited this user from being saved:</h2>
<p>There were problems with the following fields:</p>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb

<% unless @feed_items.empty? %>
<%= paginate @feed_items %>
<table class="microposts">
<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
</table>



<% end %>

app/views/shared/_feed_item.html.erb
<tr>
<td class="gravatar">
<%= link_to gravatar_for(feed_item.user), feed_item.user %>
</td>
<td class="micropost">
<span class="user">
<%= link_to feed_item.user.name, feed_item.user %>
</span>
<span class="content"><%= feed_item.content %></span>
<span class="timestamp">
Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
</span>
</td>
<% if current_user?(feed_item.user) %>
<td>
<%= link_to "delete", feed_item, :method => :delete,
:confirm => "You sure?",
:title => feed_item.content %>
</td>
<% end %>
</tr>

app/views/shared/_micropost_form.html.erb

<%= form_for @micropost do |f| %>


<div class="field">
<%= f.text_area :content, :placeholder=> "what's up" %>
</div>
</br>
<div class="actions">
<%= f.submit "Submit" %>
</div>
<% end %>

app/views/shared/_user_info.html.erb

<% @user ||= current_user %>
<div class="user_info">
<a href="<%= user_path(current_user) %>">
<%= gravatar_for current_user, :size => 30 %>
<span class="user_name">

</span>
<ul class="menu2">

<li class="item3"><%= current_user.name %></a>
	<ul>			
			</ul>
 </li>
 <li class="item2"><a href="#">micropost<span><%= pluralize(current_user.microposts.count, "") %></span></a>
			
 </li>
  <li class="item2"><a href="<%= following_user_path (@user) %> ">following<span><%= @user.following.count %></span></a>
</li>
  <li class="item2"><a href="<%= followers_user_path (@user) %> ">follower<span><%= pluralize(@user.followers.count, "") %></span></a>
			
 </li>


</ul>

</a>
		
</div>