config/routes.rb
Smart::Application.routes.draw do

  resources :users do
  member do
    get :following, :followers
  end
end
  get "password_resets/new"

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
   resources :password_resets
   resources :microposts, :only => [:create, :destroy]
   resources :relationships, :only => [:create, :destroy]

match '/contact', :to => 'pages#contact'
match '/about', :to => 'pages#about'
match '/help', :to => 'pages#help'
match '/front', :to => 'pages#front'

root :to => 'pages#home'

match '/signup', :to => 'users#new'
match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
 <div id="footer" class="section">
            	<div class="footercol">


<div class="wrapper-demo">
<div id="dd" class="wrapper-dropdown-3" tabindex="1">
  <span>User Login</span>
  <ul class="dropdown">
    <li><a href="#"><i class="icon-envelope icon-large"></i>Classic mail</a></li>
    <li><a href="#"><i class="icon-truck icon-large"></i>UPS Delivery</a></li>
    <li><a href="#"><i class="icon-plane icon-large"></i>Private jet</a></li>
  </ul>
</div>
</div>                
           	    </div>
              <div class="footercol">
               	<h5 class="fancy">Masmet for users</h5>
                 <ul>
               		  <li><a href="#">Features</a></li>
                   		<li><a href="#">Customer Acquisition</a></li>
                   		<li><a href="#">Trades</a></li>
                   		<li><a href="#">Security</a></li>
                        <li><a href="#">Dashboard</a></li>
                        <li><a href="#">Merchant Support</a></li>
                        <li><a href="#">Compare</a></li>

                 </ul>
                </div>
                <div class="footercol">
                	<h5 class="fancy">Support</h5>
                    <ul>
               		  <li><a href="#">Support</a></li>
                   		<li><a href="#">FAQs</a></li>
                   		<li><a href="#">Contact Us</a></li>
                   		
                 	</ul>
                 	<h5 class="fancy">User Login</h5>
                    <ul>
               		  <li><a href="#">Login</a> | <a href="#">Sign Up</a></li>
                   	
                 </ul>
                </div>
                <div class="footercol">
                	<h5 class="fancy">What is Masmet?</h5>
                
                  
                  
                </div>

              </div>

            </div>

app/views/layouts/_header.html.erb
<header>

	
<div id="head">
   
   
 
 

</div>

</div>


<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">MASMET</a>
      <div class="nav-collapse">
        <ul class="nav">
          
          
         
          
         <% if signed_in? %> 
         <li><%= link_to "Home", front_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Profile", current_user %></li>
         <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <% end %> 
          <% if signed_in? %>
<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
<% else %>
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Sign in", signin_path %></li>
 
<% end %>

 
        </ul>
      </div>
    </div>
  </div>
</div>

</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->


<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'application', :media => 'all' %>
<%= stylesheet_link_tag 'gh-buttons', :media => 'screen' %>
<%= stylesheet_link_tag 'bootstrap', :media => 'screen' %>
<%= stylesheet_link_tag 'bootstrap-responsive.min', :media => 'screen' %>
<%= stylesheet_link_tag 'bootstrap-responsive', :media => 'screen' %>
<%= stylesheet_link_tag 'bootstrap_and_overrides', :media => 'screen' %>
<%= javascript_include_tag "slider" %>
<%= javascript_include_tag "jquery-1.7.1.min" %>
<%= javascript_include_tag "modern" %>
<%= javascript_include_tag "jquery-1.8.2" %>
<%= javascript_include_tag "rails" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= title %></title>

<%= render 'layouts/stylesheets' %>

</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
<section class="round">
<% flash.each do |key, value| %>
<div class="flash <%= key %>"><%= value %></div>
<% end %>
<%= yield %>
<script type="text/javascript">
$(function() {
    var menu2_ul = $('.menu2 > li > ul'),
        menu2_a  = $('.menu2 > li > a');
    menu2_ul.hide();
    menu2_a.click(function(e) {
        e.preventDefault();
        if(!$(this).hasClass('active')) {
            menu2_a.removeClass('active');
            menu2_ul.filter(':visible').slideUp('normal');
            $(this).addClass('active').next().stop(true,true).slideDown('normal');
        } else {
            $(this).removeClass('active');
            $(this).next().stop(true,true).slideUp('normal');
        }
    });
});
</script>

</section>

<%= render 'layouts/footer' %>


</div>

</body>

</html>